name: observability

services:
- name: viewer
  executable: dapr
  args: run --app-id viewer --app-port 8088 --components-path ./components/local -- java -jar ./src/java_viewer/target/app.jar

- name: processor
  executable: dapr
  args: run --app-id processor --app-port 5030 --components-path ./components/local -- dotnet run --project ./src/csharp_processor/processor.csproj --urls "http://localhost:5030"
  env_file:
    - ../components/local/local.env

- name: provider
  executable: dapr
  args: run --app-id provider --app-port 5040 --components-path ./components/local -- dotnet run --project ./src/csharp_provider/provider.csproj --urls "http://localhost:5040"